version = 1

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]
  environment = [
    "nodejs",
    "vitest",
    "browser"
  ]

[[code_formatters]]
name = "prettier"